version: '3.2'

services:
  python:
    image: ex1/python:1.0
    build: ./python
    container_name: 'ex1_python'
    stdin_open: true
    tty: true
    working_dir: '/tmp/work'
    volumes:
    - ../python:/tmp/work